# Generated by Django 5.0.6 on 2024-05-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_like_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='blog.comment'),
        ),
    ]
