# Generated by Django 5.0.6 on 2024-05-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parents',
            field=models.ManyToManyField(blank=True, to='blog.comment'),
        ),
    ]
