# Generated by Django 5.0.6 on 2024-05-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.BooleanField(default=False),
        ),
    ]
