# Generated by Django 5.0.6 on 2024-05-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_liked'),
        ('blog', '0010_remove_comment_parent_remove_comment_parents'),
    ]

    operations = [
    ]
