# Generated by Django 5.0.6 on 2024-05-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_comment_parent_remove_comment_parents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replycomment',
            name='post',
        ),
    ]
